pyinstaller main.py ^
  --noconfirm ^
  --onedir ^
  --windowed ^
  --clean ^
  --optimize 2 ^
  --upx-dir="C:\upx" ^
  --exclude-module ssl ^
  --exclude-module unittest ^
  --exclude-module asyncio ^
  --exclude-module email ^
  --exclude-module http ^
  --exclude-module xml ^
  --exclude-module pydoc ^
  --exclude-module tkinter ^
  --exclude-module matplotlib ^
  --exclude-module numpy ^
  --exclude-module PIL ^
  --exclude-module PyQt6.QtWebEngine ^
  --exclude-module PyQt6.QtNetwork ^
  --name "Qt Video Compressor"